/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FinancialAuditPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  financesFolder: "Finances",
  currency: "R$",
  categories: [],
  sources: []
};

// src/settings.ts
var import_obsidian = require("obsidian");
var FinancialAuditSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Finances folder").setDesc(
      "Folder where monthly finance notes are stored. Will be created if it doesn't exist."
    ).addText(
      (text) => text.setPlaceholder("Finances").setValue(this.plugin.settings.financesFolder).onChange(async (value) => {
        this.plugin.settings.financesFolder = value || "Finances";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Currency symbol").setDesc("Symbol displayed next to amounts.").addText(
      (text) => text.setPlaceholder("R$").setValue(this.plugin.settings.currency).onChange(async (value) => {
        this.plugin.settings.currency = value || "R$";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Categories").setHeading();
    this.renderListSetting(
      containerEl,
      this.plugin.settings.categories,
      "Add category",
      "e.g. Food, Transport, Housing",
      async (updated) => {
        this.plugin.settings.categories = updated;
        await this.plugin.saveSettings();
      }
    );
    new import_obsidian.Setting(containerEl).setName("Sources").setHeading();
    this.renderListSetting(
      containerEl,
      this.plugin.settings.sources,
      "Add source",
      "e.g. Nubank, Cash, Ita\xFA",
      async (updated) => {
        this.plugin.settings.sources = updated;
        await this.plugin.saveSettings();
      }
    );
  }
  renderListSetting(containerEl, items, addLabel, placeholder, onUpdate) {
    for (let i = 0; i < items.length; i++) {
      new import_obsidian.Setting(containerEl).setName(items[i]).addButton(
        (btn) => btn.setButtonText("Remove").setWarning().onClick(async () => {
          items.splice(i, 1);
          await onUpdate([...items]);
          this.display();
        })
      );
    }
    let newValue = "";
    new import_obsidian.Setting(containerEl).addText(
      (text) => text.setPlaceholder(placeholder).onChange((value) => {
        newValue = value;
      })
    ).addButton(
      (btn) => btn.setButtonText(addLabel).setCta().onClick(async () => {
        const trimmed = newValue.trim();
        if (!trimmed || items.includes(trimmed)) return;
        items.push(trimmed);
        await onUpdate([...items]);
        this.display();
      })
    );
  }
};

// src/views/finance-view.ts
var import_obsidian6 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_FINANCE = "financial-audit-view";

// src/services/frontmatter-parser.ts
var import_obsidian2 = require("obsidian");
async function readMonthFrontmatter(app, file) {
  const content = await app.vault.read(file);
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    const data = (0, import_obsidian2.parseYaml)(match[1]);
    if (!data || !data.month) return null;
    const rawTransactions = Array.isArray(data.transactions) ? data.transactions : [];
    return {
      month: data.month,
      transactions: rawTransactions.map(
        (t) => ({
          description: t.description || "",
          amount: typeof t.amount === "number" ? t.amount : 0,
          type: t.type === "income" ? "income" : "expense",
          category: t.category || "",
          source: t.source || "",
          date: t.date || ""
        })
      )
    };
  } catch (e) {
    return null;
  }
}
async function updateMonthFrontmatter(app, file, mutator) {
  await app.fileManager.processFrontMatter(file, mutator);
}
function buildMonthNoteContent(data) {
  const yaml = (0, import_obsidian2.stringifyYaml)({
    month: data.month,
    transactions: data.transactions.map((t) => ({
      description: t.description,
      amount: t.amount,
      type: t.type,
      category: t.category,
      source: t.source,
      date: t.date
    }))
  });
  return `---
${yaml}---

## Notes
`;
}

// src/services/finance-service.ts
var FinanceService = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async getAllMonths() {
    const folder = this.settings.financesFolder;
    const files = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(folder + "/")
    );
    const entries = [];
    for (const file of files) {
      const fm = await readMonthFrontmatter(this.app, file);
      if (!fm) continue;
      const totalIncome = fm.transactions.filter((t) => t.type === "income").reduce((sum, t) => sum + t.amount, 0);
      const totalExpenses = fm.transactions.filter((t) => t.type === "expense").reduce((sum, t) => sum + t.amount, 0);
      entries.push({
        file,
        frontmatter: fm,
        totalIncome,
        totalExpenses,
        balance: totalIncome - totalExpenses
      });
    }
    return entries.sort((a, b) => b.frontmatter.month.localeCompare(a.frontmatter.month));
  }
  async getMonth(yearMonth) {
    var _a;
    const months = await this.getAllMonths();
    return (_a = months.find((m) => m.frontmatter.month === yearMonth)) != null ? _a : null;
  }
  async createMonthNote(yearMonth) {
    const folder = this.settings.financesFolder;
    const folderExists = this.app.vault.getAbstractFileByPath(folder);
    if (!folderExists) {
      await this.app.vault.createFolder(folder);
    }
    const data = {
      month: yearMonth,
      transactions: []
    };
    const path = `${folder}/${yearMonth}.md`;
    const content = buildMonthNoteContent(data);
    return await this.app.vault.create(path, content);
  }
  async getOrCreateMonth(yearMonth) {
    const existing = await this.getMonth(yearMonth);
    if (existing) return existing;
    const file = await this.createMonthNote(yearMonth);
    return {
      file,
      frontmatter: { month: yearMonth, transactions: [] },
      totalIncome: 0,
      totalExpenses: 0,
      balance: 0
    };
  }
  async addTransaction(file, transaction) {
    await updateMonthFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.transactions)) {
        data.transactions = [];
      }
      data.transactions.push({
        description: transaction.description,
        amount: transaction.amount,
        type: transaction.type,
        category: transaction.category,
        source: transaction.source,
        date: transaction.date
      });
    });
  }
  async updateTransaction(file, index, updated) {
    await updateMonthFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.transactions)) return;
      if (index < 0 || index >= data.transactions.length) return;
      data.transactions[index] = {
        description: updated.description,
        amount: updated.amount,
        type: updated.type,
        category: updated.category,
        source: updated.source,
        date: updated.date
      };
    });
  }
  async removeTransaction(file, index) {
    await updateMonthFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.transactions)) return;
      if (index < 0 || index >= data.transactions.length) return;
      data.transactions.splice(index, 1);
    });
  }
  async deleteMonth(file) {
    await this.app.fileManager.trashFile(file);
  }
};

// src/ui/summary-panel.ts
var PIE_COLORS = [
  "#4caf50",
  "#2196f3",
  "#ff9800",
  "#9c27b0",
  "#00bcd4",
  "#e91e63",
  "#8bc34a",
  "#ff5722",
  "#3f51b5",
  "#cddc39",
  "#795548",
  "#607d8b"
];
var SummaryPanelRenderer = class {
  constructor(container, month, currency) {
    this.container = container;
    this.month = month;
    this.currency = currency;
  }
  render() {
    this.container.empty();
    const wrapper = this.container.createDiv({ cls: "fa-summary" });
    const cards = wrapper.createDiv({ cls: "fa-summary-cards" });
    this.renderCard(cards, "Income", this.month.totalIncome, "fa-card-income");
    this.renderCard(cards, "Expenses", this.month.totalExpenses, "fa-card-expense");
    this.renderCard(
      cards,
      "Balance",
      this.month.balance,
      this.month.balance >= 0 ? "fa-card-positive" : "fa-card-negative"
    );
    const incomeByCategory = this.buildCategoryTotals("income");
    const expenseByCategory = this.buildCategoryTotals("expense");
    if (incomeByCategory.length > 0 || expenseByCategory.length > 0) {
      const chartsRow = wrapper.createDiv({ cls: "fa-charts-row" });
      if (incomeByCategory.length > 0) {
        this.renderPieChart(chartsRow, "Income", incomeByCategory);
      }
      if (expenseByCategory.length > 0) {
        this.renderPieChart(chartsRow, "Expenses", expenseByCategory);
      }
    }
    const categoryMap = this.buildBreakdown("category");
    if (categoryMap.size > 0) {
      this.renderBreakdownTable(wrapper, "By category", categoryMap);
    }
    const sourceMap = this.buildBreakdown("source");
    if (sourceMap.size > 0) {
      this.renderBreakdownTable(wrapper, "By source", sourceMap);
    }
  }
  renderCard(parent, label, amount, cls) {
    const card = parent.createDiv({ cls: `fa-card ${cls}` });
    card.createDiv({ text: label, cls: "fa-card-label" });
    card.createDiv({
      text: `${this.currency} ${this.formatAmount(amount)}`,
      cls: "fa-card-value"
    });
  }
  buildBreakdown(field) {
    var _a;
    const map = /* @__PURE__ */ new Map();
    for (const t of this.month.frontmatter.transactions) {
      const key = t[field] || "Uncategorized";
      const entry = (_a = map.get(key)) != null ? _a : { income: 0, expense: 0 };
      if (t.type === "income") {
        entry.income += t.amount;
      } else {
        entry.expense += t.amount;
      }
      map.set(key, entry);
    }
    return map;
  }
  renderBreakdownTable(parent, title, data) {
    const section = parent.createDiv({ cls: "fa-breakdown" });
    section.createEl("h4", { text: title, cls: "fa-breakdown-title" });
    const table = section.createEl("table", { cls: "fa-breakdown-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["Name", "Income", "Expenses", "Net"].forEach(
      (text) => headerRow.createEl("th", { text })
    );
    const tbody = table.createEl("tbody");
    for (const [name, values] of data) {
      const row = tbody.createEl("tr");
      row.createEl("td", { text: name });
      row.createEl("td", {
        text: `${this.currency} ${this.formatAmount(values.income)}`,
        cls: "fa-amount-income"
      });
      row.createEl("td", {
        text: `${this.currency} ${this.formatAmount(values.expense)}`,
        cls: "fa-amount-expense"
      });
      const net = values.income - values.expense;
      row.createEl("td", {
        text: `${this.currency} ${this.formatAmount(net)}`,
        cls: net >= 0 ? "fa-amount-positive" : "fa-amount-negative"
      });
    }
  }
  buildCategoryTotals(type) {
    var _a;
    const map = /* @__PURE__ */ new Map();
    for (const t of this.month.frontmatter.transactions) {
      if (t.type !== type) continue;
      const key = t.category || "Uncategorized";
      map.set(key, ((_a = map.get(key)) != null ? _a : 0) + t.amount);
    }
    return Array.from(map.entries()).map(([name, amount]) => ({ name, amount })).sort((a, b) => b.amount - a.amount);
  }
  renderPieChart(parent, title, slices) {
    const total = slices.reduce((sum, s) => sum + s.amount, 0);
    if (total === 0) return;
    const chartContainer = parent.createDiv({ cls: "fa-pie-container" });
    chartContainer.createEl("h4", { text: title, cls: "fa-pie-title" });
    const size = 140;
    const cx = size / 2;
    const cy = size / 2;
    const radius = 55;
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("width", size.toString());
    svg.setAttribute("height", size.toString());
    svg.setAttribute("viewBox", `0 0 ${size} ${size}`);
    svg.classList.add("fa-pie-svg");
    let startAngle = -Math.PI / 2;
    for (let i = 0; i < slices.length; i++) {
      const slice = slices[i];
      const sliceAngle = slice.amount / total * 2 * Math.PI;
      const endAngle = startAngle + sliceAngle;
      const x1 = cx + radius * Math.cos(startAngle);
      const y1 = cy + radius * Math.sin(startAngle);
      const x2 = cx + radius * Math.cos(endAngle);
      const y2 = cy + radius * Math.sin(endAngle);
      const largeArc = sliceAngle > Math.PI ? 1 : 0;
      const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
      const d = slices.length === 1 ? `M ${cx} ${cy - radius} A ${radius} ${radius} 0 1 1 ${cx - 1e-3} ${cy - radius} Z` : `M ${cx} ${cy} L ${x1} ${y1} A ${radius} ${radius} 0 ${largeArc} 1 ${x2} ${y2} Z`;
      path.setAttribute("d", d);
      path.setAttribute("fill", PIE_COLORS[i % PIE_COLORS.length]);
      svg.appendChild(path);
      startAngle = endAngle;
    }
    chartContainer.appendChild(svg);
    const legend = chartContainer.createDiv({ cls: "fa-pie-legend" });
    for (let i = 0; i < slices.length; i++) {
      const item = legend.createDiv({ cls: "fa-pie-legend-item" });
      const swatch = item.createEl("span", { cls: "fa-pie-swatch" });
      swatch.style.backgroundColor = PIE_COLORS[i % PIE_COLORS.length];
      const pct = (slices[i].amount / total * 100).toFixed(1);
      item.createEl("span", {
        text: `${slices[i].name} (${pct}%)`,
        cls: "fa-pie-legend-label"
      });
    }
  }
  formatAmount(value) {
    return value.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }
};

// src/ui/transaction-table.ts
var import_obsidian3 = require("obsidian");
var TransactionTableRenderer = class {
  constructor(container, transactions, currency, callbacks) {
    this.container = container;
    this.transactions = transactions;
    this.currency = currency;
    this.callbacks = callbacks;
  }
  render() {
    this.container.empty();
    if (this.transactions.length === 0) {
      const empty = this.container.createDiv({ cls: "fa-empty-state" });
      empty.createEl("p", {
        text: "No transactions yet. Add one to get started!"
      });
      return;
    }
    const table = this.container.createEl("table", { cls: "fa-transaction-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["Date", "Description", "Category", "Source", "Amount", ""].forEach(
      (text) => headerRow.createEl("th", { text })
    );
    const tbody = table.createEl("tbody");
    for (let i = 0; i < this.transactions.length; i++) {
      this.renderRow(tbody, this.transactions[i], i);
    }
  }
  renderRow(tbody, t, index) {
    const rowCls = t.type === "income" ? "fa-transaction-row fa-row-income" : "fa-transaction-row fa-row-expense";
    const row = tbody.createEl("tr", { cls: rowCls });
    row.createEl("td", { text: t.date, cls: "fa-date" });
    row.createEl("td", { text: t.description, cls: "fa-description" });
    row.createEl("td", { text: t.category, cls: "fa-category" });
    row.createEl("td", { text: t.source, cls: "fa-source" });
    const amountText = t.type === "income" ? `+${this.currency} ${this.formatAmount(t.amount)}` : `-${this.currency} ${this.formatAmount(t.amount)}`;
    const amountCls = t.type === "income" ? "fa-amount-income" : "fa-amount-expense";
    row.createEl("td", { text: amountText, cls: amountCls });
    const actionsCell = row.createEl("td", { cls: "fa-actions" });
    const editBtn = actionsCell.createEl("button", {
      cls: "fa-icon-btn",
      attr: { "aria-label": "Edit transaction" }
    });
    (0, import_obsidian3.setIcon)(editBtn, "pencil");
    editBtn.addEventListener("click", () => {
      this.callbacks.onEdit(index, t);
    });
    const deleteBtn = actionsCell.createEl("button", {
      cls: "fa-icon-btn fa-delete-btn",
      attr: { "aria-label": "Delete transaction" }
    });
    (0, import_obsidian3.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", () => {
      this.callbacks.onDelete(index);
    });
  }
  formatAmount(value) {
    return value.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }
};

// src/modals/add-transaction-modal.ts
var import_obsidian4 = require("obsidian");
var AddTransactionModal = class extends import_obsidian4.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.description = "";
    this.amount = 0;
    this.type = "expense";
    this.category = "";
    this.source = "";
    this.date = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add transaction" });
    new import_obsidian4.Setting(contentEl).setName("Description").addText(
      (text) => text.setPlaceholder("e.g. Grocery shopping").onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian4.Setting(contentEl).setName("Amount").addText(
      (text) => text.setPlaceholder("0.00").onChange((value) => {
        this.amount = parseFloat(value) || 0;
      })
    );
    new import_obsidian4.Setting(contentEl).setName("Type").addDropdown(
      (dropdown) => dropdown.addOptions({
        expense: "Expense",
        income: "Income"
      }).setValue(this.type).onChange((value) => {
        this.type = value;
      })
    );
    new import_obsidian4.Setting(contentEl).setName("Category").addDropdown((dropdown) => {
      const options = { "": "-- Select --" };
      for (const cat of this.settings.categories) {
        options[cat] = cat;
      }
      dropdown.addOptions(options).setValue(this.category).onChange((value) => {
        this.category = value;
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Source").addDropdown((dropdown) => {
      const options = { "": "-- Select --" };
      for (const src of this.settings.sources) {
        options[src] = src;
      }
      dropdown.addOptions(options).setValue(this.source).onChange((value) => {
        this.source = value;
      });
    });
    new import_obsidian4.Setting(contentEl).setName("Date").addText(
      (text) => text.setValue(this.date).setPlaceholder("YYYY-MM-DD").onChange((value) => {
        this.date = value;
      })
    );
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add transaction").setCta().onClick(() => {
        if (!this.description.trim() || this.amount <= 0) {
          return;
        }
        void this.onSubmit({
          description: this.description.trim(),
          amount: this.amount,
          type: this.type,
          category: this.category,
          source: this.source,
          date: this.date
        });
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/edit-transaction-modal.ts
var import_obsidian5 = require("obsidian");
var EditTransactionModal = class extends import_obsidian5.Modal {
  constructor(app, settings, original, onSubmit) {
    super(app);
    this.settings = settings;
    this.original = original;
    this.onSubmit = onSubmit;
    this.description = original.description;
    this.amount = original.amount;
    this.type = original.type;
    this.category = original.category;
    this.source = original.source;
    this.date = original.date;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Edit transaction" });
    new import_obsidian5.Setting(contentEl).setName("Description").addText(
      (text) => text.setValue(this.description).setPlaceholder("e.g. Grocery shopping").onChange((value) => {
        this.description = value;
      })
    );
    new import_obsidian5.Setting(contentEl).setName("Amount").addText(
      (text) => text.setValue(this.amount.toString()).setPlaceholder("0.00").onChange((value) => {
        this.amount = parseFloat(value) || 0;
      })
    );
    new import_obsidian5.Setting(contentEl).setName("Type").addDropdown(
      (dropdown) => dropdown.addOptions({
        expense: "Expense",
        income: "Income"
      }).setValue(this.type).onChange((value) => {
        this.type = value;
      })
    );
    new import_obsidian5.Setting(contentEl).setName("Category").addDropdown((dropdown) => {
      const options = { "": "-- Select --" };
      for (const cat of this.settings.categories) {
        options[cat] = cat;
      }
      dropdown.addOptions(options).setValue(this.category).onChange((value) => {
        this.category = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Source").addDropdown((dropdown) => {
      const options = { "": "-- Select --" };
      for (const src of this.settings.sources) {
        options[src] = src;
      }
      dropdown.addOptions(options).setValue(this.source).onChange((value) => {
        this.source = value;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Date").addText(
      (text) => text.setValue(this.date).setPlaceholder("YYYY-MM-DD").onChange((value) => {
        this.date = value;
      })
    );
    new import_obsidian5.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save changes").setCta().onClick(() => {
        if (!this.description.trim() || this.amount <= 0) {
          return;
        }
        void this.onSubmit({
          description: this.description.trim(),
          amount: this.amount,
          type: this.type,
          category: this.category,
          source: this.source,
          date: this.date
        });
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/finance-view.ts
var ConfirmDeleteModal = class extends import_obsidian6.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    new import_obsidian6.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Delete").setWarning().onClick(async () => {
        await this.onConfirm();
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FinanceView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.monthEntry = null;
    this.plugin = plugin;
    this.financeService = new FinanceService(plugin.app, plugin.settings);
    this.currentMonth = this.getCurrentYearMonth();
  }
  getViewType() {
    return VIEW_TYPE_FINANCE;
  }
  getDisplayText() {
    return "Financial Audit";
  }
  getIcon() {
    return "wallet";
  }
  async onOpen() {
    await this.refresh();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  async refresh() {
    this.financeService = new FinanceService(this.plugin.app, this.plugin.settings);
    this.monthEntry = await this.financeService.getMonth(this.currentMonth);
    this.render();
  }
  getCurrentYearMonth() {
    const now = /* @__PURE__ */ new Date();
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, "0");
    return `${year}-${month}`;
  }
  navigateMonth(delta) {
    const [yearStr, monthStr] = this.currentMonth.split("-");
    let year = parseInt(yearStr);
    let month = parseInt(monthStr) + delta;
    if (month > 12) {
      month = 1;
      year++;
    } else if (month < 1) {
      month = 12;
      year--;
    }
    this.currentMonth = `${year}-${month.toString().padStart(2, "0")}`;
    void this.refresh();
  }
  formatMonthLabel(yearMonth) {
    const [year, month] = yearMonth.split("-");
    const date = new Date(parseInt(year), parseInt(month) - 1);
    return date.toLocaleString("default", { month: "long", year: "numeric" });
  }
  render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("fa-container");
    const toolbar = container.createDiv({ cls: "fa-toolbar" });
    const navLeft = toolbar.createEl("button", {
      cls: "fa-btn fa-nav-btn",
      attr: { "aria-label": "Previous month" }
    });
    (0, import_obsidian6.setIcon)(navLeft, "chevron-left");
    navLeft.addEventListener("click", () => this.navigateMonth(-1));
    toolbar.createEl("span", {
      text: this.formatMonthLabel(this.currentMonth),
      cls: "fa-month-label"
    });
    const navRight = toolbar.createEl("button", {
      cls: "fa-btn fa-nav-btn",
      attr: { "aria-label": "Next month" }
    });
    (0, import_obsidian6.setIcon)(navRight, "chevron-right");
    navRight.addEventListener("click", () => this.navigateMonth(1));
    const addBtn = toolbar.createEl("button", {
      text: "Add transaction",
      cls: "fa-btn fa-btn-primary"
    });
    (0, import_obsidian6.setIcon)(addBtn, "plus");
    addBtn.prepend(addBtn.querySelector(".svg-icon"));
    addBtn.addEventListener("click", () => this.openAddModal());
    const popoutBtn = toolbar.createEl("button", {
      cls: "fa-btn",
      attr: { "aria-label": "Open in popout window" }
    });
    (0, import_obsidian6.setIcon)(popoutBtn, "external-link");
    popoutBtn.addEventListener("click", () => {
      void this.plugin.activatePopoutView();
    });
    const content = container.createDiv({ cls: "fa-content" });
    if (!this.monthEntry || this.monthEntry.frontmatter.transactions.length === 0) {
      if (!this.monthEntry) {
        const empty = content.createDiv({ cls: "fa-empty-state" });
        empty.createEl("p", {
          text: "No data for this month yet. Add a transaction to get started!"
        });
      } else {
        const summaryContainer2 = content.createDiv({ cls: "fa-summary-section" });
        new SummaryPanelRenderer(
          summaryContainer2,
          this.monthEntry,
          this.plugin.settings.currency
        ).render();
        const empty = content.createDiv({ cls: "fa-empty-state" });
        empty.createEl("p", {
          text: "No transactions this month. Add one!"
        });
      }
      return;
    }
    const summaryContainer = content.createDiv({ cls: "fa-summary-section" });
    new SummaryPanelRenderer(
      summaryContainer,
      this.monthEntry,
      this.plugin.settings.currency
    ).render();
    const tableContainer = content.createDiv({ cls: "fa-table-section" });
    tableContainer.createEl("h4", { text: "Transactions", cls: "fa-section-title" });
    new TransactionTableRenderer(
      tableContainer,
      this.monthEntry.frontmatter.transactions,
      this.plugin.settings.currency,
      {
        onEdit: (index, transaction) => this.openEditModal(index, transaction),
        onDelete: (index) => this.handleDelete(index)
      }
    ).render();
  }
  openAddModal() {
    new AddTransactionModal(
      this.app,
      this.plugin.settings,
      async (transaction) => {
        const entry = await this.financeService.getOrCreateMonth(
          this.currentMonth
        );
        await this.financeService.addTransaction(entry.file, transaction);
        await this.refresh();
      }
    ).open();
  }
  openEditModal(index, transaction) {
    if (!this.monthEntry) return;
    const file = this.monthEntry.file;
    new EditTransactionModal(
      this.app,
      this.plugin.settings,
      transaction,
      async (updated) => {
        await this.financeService.updateTransaction(file, index, updated);
        await this.refresh();
      }
    ).open();
  }
  handleDelete(index) {
    if (!this.monthEntry) return;
    const file = this.monthEntry.file;
    const t = this.monthEntry.frontmatter.transactions[index];
    new ConfirmDeleteModal(
      this.app,
      `Delete transaction "${t.description}" (${this.plugin.settings.currency} ${t.amount.toFixed(2)})?`,
      async () => {
        await this.financeService.removeTransaction(file, index);
        await this.refresh();
      }
    ).open();
  }
};

// src/main.ts
var FinancialAuditPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_FINANCE,
      (leaf) => new FinanceView(leaf, this)
    );
    this.addRibbonIcon("wallet", "Open Financial Audit", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-financial-audit",
      name: "Open tracker",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "open-financial-audit-popout",
      name: "Open tracker in popout window",
      callback: () => {
        void this.activatePopoutView();
      }
    });
    this.addCommand({
      id: "add-transaction",
      name: "Add transaction",
      callback: () => {
        const now = /* @__PURE__ */ new Date();
        const yearMonth = `${now.getFullYear()}-${(now.getMonth() + 1).toString().padStart(2, "0")}`;
        const service = new FinanceService(this.app, this.settings);
        new AddTransactionModal(
          this.app,
          this.settings,
          async (transaction) => {
            const entry = await service.getOrCreateMonth(yearMonth);
            await service.addTransaction(entry.file, transaction);
            this.refreshFinanceView();
          }
        ).open();
      }
    });
    this.addSettingTab(new FinancialAuditSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian7.TFile && file.path.startsWith(this.settings.financesFolder + "/")) {
          this.refreshFinanceView();
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      saved != null ? saved : {}
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_FINANCE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_FINANCE,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  async activatePopoutView() {
    const leaf = this.app.workspace.openPopoutLeaf();
    await leaf.setViewState({
      type: VIEW_TYPE_FINANCE,
      active: true
    });
    void this.app.workspace.revealLeaf(leaf);
  }
  refreshFinanceView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_FINANCE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && typeof view.refresh === "function") {
        void view.refresh();
      }
    }
  }
};
